# Generated by Django 5.1.5 on 2025-01-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.IntegerField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
